2022-04-11 14:17:35,006 INFO    MainThread:6360 [wandb_setup.py:_flush():75] Loading settings from C:\Users\inu\.config\wandb\settings
2022-04-11 14:17:35,007 INFO    MainThread:6360 [wandb_setup.py:_flush():75] Loading settings from c:\Users\inu\Documents\ia\trabajo practico 1\wandb\settings
2022-04-11 14:17:35,008 INFO    MainThread:6360 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-11 14:17:35,008 INFO    MainThread:6360 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-11 14:17:35,009 INFO    MainThread:6360 [wandb_setup.py:_flush():75] Applying login settings: {'api_key': '***REDACTED***'}
2022-04-11 14:17:35,012 INFO    MainThread:6360 [wandb_init.py:_log_setup():438] Logging user logs to c:\Users\inu\Documents\ia\trabajo practico 1\wandb\run-20220411_141734-fitfn8g9\logs\debug.log
2022-04-11 14:17:35,029 INFO    MainThread:6360 [wandb_init.py:_log_setup():439] Logging internal logs to c:\Users\inu\Documents\ia\trabajo practico 1\wandb\run-20220411_141734-fitfn8g9\logs\debug-internal.log
2022-04-11 14:17:35,030 INFO    MainThread:6360 [wandb_init.py:init():472] calling init triggers
2022-04-11 14:17:35,031 INFO    MainThread:6360 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {}
2022-04-11 14:17:35,032 INFO    MainThread:6360 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 1e8yzg5g
2022-04-11 14:17:35,036 INFO    MainThread:6360 [wandb_run.py:_finish():1684] finishing run ml_ialab/test-project/1e8yzg5g
2022-04-11 14:17:35,479 INFO    MainThread:6360 [jupyter.py:save_history():432] not saving jupyter history
2022-04-11 14:17:35,480 INFO    MainThread:6360 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-04-11 14:17:35,480 INFO    MainThread:6360 [wandb_init.py:_jupyter_teardown():370] cleaning up jupyter logic
2022-04-11 14:17:35,480 INFO    MainThread:6360 [wandb_run.py:_atexit_cleanup():1865] got exitcode: 0
2022-04-11 14:17:35,484 INFO    MainThread:6360 [wandb_run.py:_restore():1837] restore
2022-04-11 14:17:36,065 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 837
}

2022-04-11 14:17:36,474 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 837
}

2022-04-11 14:17:37,018 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 837
}

2022-04-11 14:17:37,148 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 9173
}

2022-04-11 14:17:37,305 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 9173
}

2022-04-11 14:17:37,471 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 9173
}

2022-04-11 14:17:37,653 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 837
  total_bytes: 9173
}

2022-04-11 14:17:37,823 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 6252
  total_bytes: 9173
}

2022-04-11 14:17:38,072 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:38,248 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:38,418 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:38,585 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:38,770 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:39,687 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}

2022-04-11 14:17:40,537 INFO    MainThread:6360 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9173
  total_bytes: 9173
}
local_info {
}

2022-04-11 14:17:42,639 INFO    MainThread:6360 [wandb_run.py:_footer_history_summary_info():3087] rendering history
2022-04-11 14:17:42,639 INFO    MainThread:6360 [wandb_run.py:_footer_history_summary_info():3116] rendering summary
2022-04-11 14:17:42,646 INFO    MainThread:6360 [wandb_run.py:_footer_sync_info():3044] logging synced files
2022-04-11 14:17:42,662 INFO    MainThread:6360 [wandb_init.py:init():525] starting backend
2022-04-11 14:17:42,665 INFO    MainThread:6360 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-04-11 14:17:42,688 INFO    MainThread:6360 [backend.py:ensure_launched():219] starting backend process...
2022-04-11 14:17:43,164 INFO    MainThread:6360 [backend.py:ensure_launched():224] started backend process with pid: 2264
2022-04-11 14:17:43,166 INFO    MainThread:6360 [wandb_init.py:init():534] backend started and connected
2022-04-11 14:17:43,223 INFO    MainThread:6360 [wandb_run.py:_label_probe_notebook():1082] probe notebook
2022-04-11 14:17:43,224 INFO    MainThread:6360 [wandb_run.py:_label_probe_notebook():1092] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-04-11 14:17:43,224 INFO    MainThread:6360 [wandb_init.py:init():598] updated telemetry
2022-04-11 14:17:43,232 INFO    MainThread:6360 [wandb_init.py:init():629] communicating run to backend with 30 second timeout
2022-04-11 14:17:51,091 INFO    MainThread:6360 [wandb_run.py:_on_init():1922] communicating current version
2022-04-11 14:17:51,402 INFO    MainThread:6360 [wandb_run.py:_on_init():1926] got version response 
2022-04-11 14:17:51,403 INFO    MainThread:6360 [wandb_init.py:init():660] starting run threads in backend
2022-04-11 14:17:56,431 INFO    MainThread:6360 [wandb_run.py:_console_start():1896] atexit reg
2022-04-11 14:17:56,433 INFO    MainThread:6360 [wandb_run.py:_redirect():1769] redirect: SettingsConsole.WRAP
2022-04-11 14:17:56,433 INFO    MainThread:6360 [wandb_run.py:_redirect():1806] Wrapping output streams.
2022-04-11 14:17:56,442 INFO    MainThread:6360 [wandb_run.py:_redirect():1830] Redirects installed.
2022-04-11 14:17:56,442 INFO    MainThread:6360 [wandb_init.py:init():685] run started, returning control to user process
